name: quran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  flutter: 
    sdk: flutter
  lottie: ^2.6.0
  http: ^1.1.0
  get_storage: ^2.1.1
  just_audio: ^0.9.37

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/lotties/
    - assets/images/

